[shell]
avatar_path = "/home/supardi/Projects/dotfiles/dotconfig/wallpapers/44753.jpg"
font_family = "JetBrainsMono Nerd Font"
card_borders = false
button_borders = false
input_borders = true
popup_borders = true
popup_shadows = true
settings_window_translucent = true

[shell.animation]
enabled = true
speed = 1.0

[shell.launcher]
categories = true
show_icons = true
sort_by_usage = true
auto_paste = "auto"
compact = true

[shell.panel]
transparency_mode = "soft"
list_item_background = false
borders = true
shadow = true
control_center_placement = "floating"
control_center_position = "top_right"
launcher_position = "bottom_center"
session_position = "top_right"
open_near_click_control_center = false
open_near_click_clipboard = false
open_near_click_session = true
floating_offset = 12

[shell.window_switcher]
style = "carousel"
show_all_outputs = true
show_app_icon = true
show_caption = true

[dock]
launcher_icon = "pacman"

[notification]
background_opacity = 0.55
border_color = "secondary"

[osd]
background_opacity = 0.55

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"
community_palette = "Oxocarbon"
pure_black_dark = true

[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = [ "niri", "kitty", "gtk3", "gtk4", "qt", "btop" ]
community_ids = [ "spicetify" ]

[wallpaper]
enabled = true
directory = "/home/supardi/Projects/dotfiles/dotconfig/wallpapers"
directory_dark = "/home/supardi/Projects/dotfiles/dotconfig/wallpapers"
fill_mode = "crop"
transition = [ "fade", "wipe", "disc" ]
transition_duration = 1000.0

[wallpaper.default]
path = "/home/supardi/Projects/dotfiles/dotconfig/wallpapers/1363137.png"

[wallpaper.last]
path = "/home/supardi/Projects/dotfiles/dotconfig/wallpapers/1363137.png"

[bar]
order = [ "default" ]

[bar.default]
position = "top"
thickness = 32.0
auto_hide = false
background_opacity = 0.55
compositor_blur = true
concave_edge_corners = false
margin_edge = 8
margin_ends = 150
radius = 12
capsule = false
widget_spacing = 8

start = [ "launcher", "date", "cpu", "active_window" ]
center = [ "workspaces" ]
end = [ "media", "tray", "brightness", "volume", "battery", "network", "notifications", "control-center" ]



[widget.date]
format = "{:%H:%M  %a, %b %d}"

[widget.active_window]
display = "icon_and_text"
max_length = 260.0
min_length = 80.0
title_scroll = "on_hover"


[widget.active_window.actions]
scroll_up = "exec niri msg action focus-column-left"
scroll_down = "exec niri msg action focus-column-right"


[widget.media]
hide_when_no_media = false
title_scroll = "always"




[widget.control-center]
glyph = "adjustments-horizontal"
