
$background = rgba(16130bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(343027ff)

$inverse_primary = rgba(725c0cff)

$inverse_surface = rgba(eae2d4ff)

$on_background = rgba(eae2d4ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3c2f00ff)

$on_primary_container = rgba(ffe086ff)

$on_primary_fixed = rgba(231b00ff)

$on_primary_fixed_variant = rgba(574500ff)

$on_secondary = rgba(383016ff)

$on_secondary_container = rgba(f1e1bbff)

$on_secondary_fixed = rgba(221b04ff)

$on_secondary_fixed_variant = rgba(50462aff)

$on_surface = rgba(eae2d4ff)

$on_surface_variant = rgba(cec6b4ff)

$on_tertiary = rgba(183720ff)

$on_tertiary_container = rgba(c8eccaff)

$on_tertiary_fixed = rgba(02210cff)

$on_tertiary_fixed_variant = rgba(2f4e35ff)

$outline = rgba(979080ff)

$outline_variant = rgba(4c4639ff)

$primary = rgba(e1c46dff)

$primary_container = rgba(574500ff)

$primary_fixed = rgba(ffe086ff)

$primary_fixed_dim = rgba(e1c46dff)

$scrim = rgba(000000ff)

$secondary = rgba(d4c5a1ff)

$secondary_container = rgba(50462aff)

$secondary_fixed = rgba(f1e1bbff)

$secondary_fixed_dim = rgba(d4c5a1ff)

$shadow = rgba(000000ff)

$source_color = rgba(f3d57cff)

$surface = rgba(16130bff)

$surface_bright = rgba(3d392fff)

$surface_container = rgba(231f17ff)

$surface_container_high = rgba(2d2a21ff)

$surface_container_highest = rgba(38342bff)

$surface_container_low = rgba(1e1b13ff)

$surface_container_lowest = rgba(110e07ff)

$surface_dim = rgba(16130bff)

$surface_tint = rgba(e1c46dff)

$surface_variant = rgba(4c4639ff)

$tertiary = rgba(accfafff)

$tertiary_container = rgba(2f4e35ff)

$tertiary_fixed = rgba(c8eccaff)

$tertiary_fixed_dim = rgba(accfafff)


