# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#eae2d4"

# Title color for boxes
theme[title]="#e1c46d"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d4c5a1"

# Background color of selected item in processes box
theme[selected_bg]="#e1c46d"

# Foreground color of selected item in processes box
theme[selected_fg]="#3c2f00"

# Color of inactive/disabled text
theme[inactive_fg]="#cec6b4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#accfaf"

# Cpu box outline color
theme[cpu_box]="#979080"

# Memory/disks box outline color
theme[mem_box]="#979080"

# Net up/down box outline color
theme[net_box]="#979080"

# Processes box outline color
theme[proc_box]="#979080"

# Box divider line and small boxes line color
theme[div_line]="#4c4639"

# Temperature graph colors
theme[temp_start]="#d4c5a1"
theme[temp_mid]="#e1c46d"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d4c5a1"
theme[cpu_mid]="#e1c46d"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d4c5a1"
theme[free_mid]=""
theme[free_end]="#50462a"

# Mem/Disk cached meter
theme[cached_start]="#accfaf"
theme[cached_mid]=""
theme[cached_end]="#2f4e35"

# Mem/Disk available meter
theme[available_start]="#e1c46d"
theme[available_mid]=""
theme[available_end]="#574500"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d4c5a1"
theme[download_mid]="#e1c46d"
theme[download_end]="#accfaf"

# Upload graph colors
theme[upload_start]="#d4c5a1"
theme[upload_mid]="#e1c46d"
theme[upload_end]="#accfaf"