#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#
# CUSTOM CONFIGURATION VARIATION
# -----------------------------------------------------

# Path ke Project Ricing
$project_dir = $HOME/.config/hypr

# Gunakan Kitty dengan konfigurasi Glassy macOS dari project ini
# Bind ini akan dikelola di keybindings/default.conf agar tidak double

# Efek tambahan untuk ricing
windowrule {
    name = kitty
    match:class = ^(kitty)$
    opacity = 0.85 0.85
}
layerrule2 = blur, waybar
