# -----------------------------------------------------
# Plugins Configuration
# -----------------------------------------------------

plugin {
    hyprbars {
        # Style settings
        bar_height = 25
        bar_color = rgba(1e1e2ecc)
        col.text = rgba(ffffffff)
        bar_text_size = 10
        bar_text_font = "JetBrainsMono Nerd Font"
        bar_button_padding = 12
        bar_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true

        # Buttons (macOS Style)
        # Format: color, size, icon, command
        hyprbars-button = rgba(ff5f56ff), 12, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgba(27c93fff), 12, 󰖯, hyprctl dispatch fullscreen 1
    }

    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgba(181825ff)
        workspace_method = center current # [center current/first or [workspace] [unfocused]]

        enable_gesture = true # laptop gestures
    }
}
