#    __  _____  _____      __  _____          ___
#   /  |/  / / / / / | /| / / / ___/__  ___  / _/
#  / /|_/ / /_/_  _/ |/ |/ / / /__/ _ \/ _ \/ _/
# /_/  /_/____//_/ |__/|__/  \___/\___/_//_/_/
#

# SwayNC
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

# Pavucontrol
windowrule {
    name = pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)
    float = true
    center = true
    pin = true
    size = 700 600
}

# Waypaper
windowrule {
    name = waypaper
    match:class = (.*waypaper.*)
    float = true
    center = true
    pin = true
    size = 900 700
}

# Newelle
windowrule {
    name = newelle
    match:class = (io.github.qwersyk.Newelle)
    float = true
    center = true
    pin = true
    size = 1000 700
}

# Ricing Pro Calendar
windowrule {
    name = ricing-calendar
    match:class = (com.ml4w.calendar)
    float = true
    move = 21 76
    pin = true
    size = 400 400
}

# Ricing Pro Settings
windowrule {
    name = ricing-settings
    match:class = (com.ml4w.hyprlandsettings)
    float = true
    move = monitor_w*0.5-window_w*0.5 monitor_h*0.5-window_h*0.5
    pin = true
    size = 800 600
}

# Blueman Manager
windowrule {
    name = blueman-manager
    match:class = (blueman-manager)
    float = true
    center = true
    size = 800 600
}

# nwg-look
windowrule {
    name = nwg-look
    match:class = (nwg-look)
    float = true
    center = true
    size = 700 600
}

# nwg-displays
windowrule {
    name = nwg-displays
    match:class = (nwg-displays)
    float = true
    center = true
    size = 900 600
}

# System Mission Center
windowrule {
    name = missioncenter
    match:class = (io.missioncenter.MissionCenter)
    float = true
    center = true
    pin = true
    size = 900 600
}

# Gnome Calculator
windowrule {
    name = gnome-calculator
    match:class = (org.gnome.Calculator)
    float = true
    center = true
    size = 700 600
}

# Omcalc (Modern Calculator)
windowrule {
    name = omcalc
    match:title = (Omcalc)
    float = true
    center = true
    size = 1000 700
}

# Spotify
windowrule {
    name = spotify
    match:class = (spotify)
    float = true
    center = true
    size = 1000 700
}

# Hyprland Share Picker
windowrule {
    name = hyprland-share-picker
    match:class = (hyprland-share-picker)
    float = true
    pin = true
    center = true
    size = 600 400
}

# nm-connection-editor
windowrule {
    name = nm-connection-editor
    match:class = (nm-connection-editor)
    float = true
    center = true
    size = 800 700
}

# Picture-in-Picture
windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}

# General floating
windowrule {
    name = dotfiles-floating
    match:class = (dotfiles-floating)
    float = true
    center = true
    size = 1000 700
}

# Float and center file pickers
windowrule {
    name = file-picker
    match:title = ^(.Open.*Files?|Save.*Files?|All Files|Save)
    float = true
    center = true
}

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
# env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# XWayland
xwayland {
  force_zero_scaling = true
}

# SDL version
env = SDL_VIDEODRIVER,wayland
