# -----------------------------------------------------
# 🚀 Native Sidebar Rules
# -----------------------------------------------------

# Aturan umum agar special workspace (sidebar) selalu melayang dan rapi
workspace = special:sidebar, gapsout:60, gapsin:30, border:true, shadow:true

# Window rules
# -----------------------------------------------------

# Waybar Blur
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.3, match:namespace waybar

# Rofi Blur
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.3, match:namespace rofi
layerrule = animation popin 80%, match:namespace rofi







