color0 #414750
color1 #ffb4ab
color2 #9ecaff
color3 #b4c8e5
color4 #efb1fb
color5 #9ecaff
color6 #b4c8e5
color7 #e1e2e8
color8 #8b919b
color9 #ffb4ab
color10 #9ecaff
color11 #b4c8e5
color12 #efb1fb
color13 #9ecaff
color14 #b4c8e5
color15 #e1e2e8

cursor                #e1e2e8
cursor_text_color     #111417
background            #111417
foreground            #e1e2e8
selection_foreground  #c1c7d1
selection_background  #414750
active_border_color   #9ecaff
inactive_border_color #414750
url_color             #9ecaff

active_tab_foreground   #003258
active_tab_background   #9ecaff
inactive_tab_foreground #c1c7d1
inactive_tab_background #414750
cursor_trail_color      #c1c7d1
