color0 #44474c
color1 #ffb4ab
color2 #bbc7dd
color3 #c3c6d0
color4 #d8bfd5
color5 #bbc7dd
color6 #c3c6d0
color7 #e4e2e3
color8 #8f9197
color9 #ffb4ab
color10 #bbc7dd
color11 #c3c6d0
color12 #d8bfd5
color13 #bbc7dd
color14 #c3c6d0
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #000000
background            #000000
foreground            #e4e2e3
selection_foreground  #c5c6cd
selection_background  #44474c
active_border_color   #bbc7dd
inactive_border_color #373a3e
url_color             #bbc7dd

active_tab_foreground   #253142
active_tab_background   #bbc7dd
inactive_tab_foreground #c5c6cd
inactive_tab_background #373a3e
cursor_trail_color      #c5c6cd
