color0 #42474c
color1 #ffb4ab
color2 #accae4
color3 #bcc8d3
color4 #dcbce0
color5 #accae4
color6 #bcc8d3
color7 #e3e2e4
color8 #8c9197
color9 #ffb4ab
color10 #accae4
color11 #bcc8d3
color12 #dcbce0
color13 #accae4
color14 #bcc8d3
color15 #e3e2e4

cursor                #e3e2e4
cursor_text_color     #121315
background            #121315
foreground            #e3e2e4
selection_foreground  #c2c7cd
selection_background  #42474c
active_border_color   #accae4
inactive_border_color #42474c
url_color             #accae4

active_tab_foreground   #133348
active_tab_background   #accae4
inactive_tab_foreground #c2c7cd
inactive_tab_background #42474c
cursor_trail_color      #c2c7cd
